### TESS Objects of Interest
This dataset is a comprehensive list of all confirmed exoplanets, planetary candidates (PC), false positives (FP), ambiguous planetary candidates (APC), and known planets (KP, previously identified) identified by the TESS mission so far. See column “TFOWPG Disposition” for classification.  
Explanation of each column name is in [the dataset](datasets/TOI.csv)

In [1]:
import pandas as pd

In [2]:
url = 'datasets/TOI.csv'
tess_df = pd.read_csv(url, comment='#')
tess_df.head()

,toi,tid,tfopwg_disp,rastr,ra,decstr,dec,st_pmra,st_pmraerr1,st_pmraerr2,...,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_rad,st_raderr1,st_raderr2,st_radlim,toi_created,rowupdate
0,1000.01,50365310,FP,07h29m25.85s,112.357708,-12d41m45.46s,-12.695960,-5.964,0.085,-0.085,...,4.19,0.07,-0.07,0,2.16986,0.072573,-0.072573,0,2019-07-24 15:58:33,2024-09-09 10:08:01
1,1001.01,88863718,PC,08h10m19.31s,122.580465,-05d30m49.87s,-5.513852,-4.956,0.102,-0.102,...,4.03,0.09,-0.09,0,2.01000,0.090000,-0.090000,0,2019-07-24 15:58:33,2023-04-03 14:31:04
2,1002.01,124709665,FP,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,-1.462,0.206,-0.206,...,NaN,NaN,NaN,0,5.73000,NaN,NaN,0,2019-07-24 15:58:33,2022-07-11 16:02:02
3,1003.01,106997505,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,-0.939,0.041,-0.041,...,4.15,1.64,-1.64,0,NaN,NaN,NaN,0,2019-07-24 15:58:33,2022-02-23 10:10:02
4,1004.01,238597883,FP,08h08m42.77s,122.178195,-48d48m10.12s,-48.802811,-4.496,0.069,-0.069,...,4.14,0.07,-0.07,0,2.15000,0.060000,-0.060000,0,2019-07-24 15:58:33,2024-09-09 10:08:01

In [4]:
tess_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 65 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   toi              7668 non-null   float64
 1   tid              7668 non-null   int64
 2   tfopwg_disp      7668 non-null   object
 3   rastr            7668 non-null   object
 4   ra               7668 non-null   float64
 5   decstr           7668 non-null   object
 6   dec              7668 non-null   float64
 7   st_pmra          7534 non-null   float64
 8   st_pmraerr1      7534 non-null   float64
 9   st_pmraerr2      7534 non-null   float64
 10  st_pmralim       7534 non-null   float64
 11  st_pmdec         7534 non-null   float64
 12  st_pmdecerr1     7534 non-null   float64
 13  st_pmdecerr2     7534 non-null   float64
 14  st_pmdeclim      7534 non-null   float64
 15  pl_tranmid       7668 non-null   float64
 16  pl_tranmiderr1   7657 non-null   float64
 17  pl_tranmiderr2   7657 non-null   float64
 18  pl_tranmidlim    7668 non-null   int64
 19  pl_orbper        7562 non-null   float64
 20  pl_orbpererr1    7538 non-null   float64
 21  pl_orbpererr2    7538 non-null   float64
 22  pl_orbperlim     7668 non-null   int64
 23  pl_trandurh      7668 non-null   float64
 24  pl_trandurherr1  7655 non-null   float64
 25  pl_trandurherr2  7655 non-null   float64
 26  pl_trandurhlim   7668 non-null   int64
 27  pl_trandep       7668 non-null   float64
 28  pl_trandeperr1   7662 non-null   float64
 29  pl_trandeperr2   7662 non-null   float64
 30  pl_trandeplim    7668 non-null   int64
 31  pl_rade          7164 non-null   float64
 32  pl_radeerr1      6047 non-null   float64
 33  pl_radeerr2      6047 non-null   float64
 34  pl_radelim       7668 non-null   int64
 35  pl_insol         7492 non-null   float64
 36  pl_insolerr1     0 non-null      float64
 37  pl_insolerr2     0 non-null      float64
 38  pl_insollim      0 non-null      float64
 39  pl_eqt           7357 non-null   float64
 40  pl_eqterr1       0 non-null      float64
 41  pl_eqterr2       0 non-null      float64
 42  pl_eqtlim        0 non-null      float64
 43  st_tmag          7668 non-null   float64
 44  st_tmagerr1      7668 non-null   float64
 45  st_tmagerr2      7668 non-null   float64
 46  st_tmaglim       7668 non-null   int64
 47  st_dist          7453 non-null   float64
 48  st_disterr1      6962 non-null   float64
 49  st_disterr2      6962 non-null   float64
 50  st_distlim       7668 non-null   int64
 51  st_teff          7507 non-null   float64
 52  st_tefferr1      7195 non-null   float64
 53  st_tefferr2      7195 non-null   float64
 54  st_tefflim       7668 non-null   int64
 55  st_logg          6812 non-null   float64
 56  st_loggerr1      5411 non-null   float64
 57  st_loggerr2      5411 non-null   float64
 58  st_logglim       7668 non-null   int64
 59  st_rad           7163 non-null   float64
 60  st_raderr1       5718 non-null   float64
 61  st_raderr2       5718 non-null   float64
 62  st_radlim        7668 non-null   int64
 63  toi_created      7668 non-null   object
 64  rowupdate        7668 non-null   object
dtypes: float64(49), int64(11), object(5)
memory usage: 3.8+ MB